export interface TestDefinition {
  code: string;
  name: string;
  department: string;
  requiredSampleType: string;
  volume: string;
  turnaroundDays: number;
  isAllergyProfile?: boolean;
}

export const TEST_CATALOG: TestDefinition[] = [
  // HAEMATOLOGY
  {
    code: "FBC",
    name: "FBC (Full Blood Count)",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 1,
  },
  {
    code: "MAL",
    name: "Malaria Parasites",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 1,
  },
  {
    code: "BGR",
    name: "Blood Group & Rhesus",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 1,
  },
  {
    code: "CD4",
    name: "CD4 Count",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 3,
  },
  {
    code: "ESR",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 1,
  },
  {
    code: "INRPT",
    name: "INR/PT (Prothrombin Time)",
    department: "Haematology",
    requiredSampleType: "Citrate Blue Top",
    volume: "2.7ml",
    turnaroundDays: 1,
  },
  {
    code: "PBF",
    name: "Peripheral Blood Film",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 2,
  },
  {
    code: "RETIC",
    name: "Reticulocyte Count",
    department: "Haematology",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 1,
  },

  // CHEMISTRY
  {
    code: "UE",
    name: "U&E (Urea & Electrolytes)",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "LFT",
    name: "LFT (Liver Function Tests)",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "LIP",
    name: "Lipid Profile",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "GLUC",
    name: "Glucose (Fasting/Random)",
    department: "Chemistry",
    requiredSampleType: "Fluoride Grey Top",
    volume: "2ml",
    turnaroundDays: 1,
  },
  {
    code: "HBA1C",
    name: "HbA1C",
    department: "Chemistry",
    requiredSampleType: "EDTA Purple Top",
    volume: "3ml",
    turnaroundDays: 2,
  },
  {
    code: "TROP",
    name: "Troponin-I",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 0,
  },
  {
    code: "CREAT",
    name: "Creatinine",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "EGFR",
    name: "eGFR",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "AMYL",
    name: "Amylase",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "MG",
    name: "Magnesium",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "PHOS",
    name: "Phosphate",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "URIC",
    name: "Uric Acid",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "CRP",
    name: "CRP (C-Reactive Protein)",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "TSH",
    name: "TFTs: TSH",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "FT3",
    name: "TFTs: FT3",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "FT4",
    name: "TFTs: FT4",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "PSA",
    name: "PSA (Prostate Specific Antigen)",
    department: "Chemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },

  // SEROLOGY / IMMUNOCHEMISTRY
  {
    code: "HIV12",
    name: "HIV 1&2 Antibody",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "HIVVL",
    name: "HIV Viral Load",
    department: "Serology / Immunochemistry",
    requiredSampleType: "EDTA Purple Top",
    volume: "6ml",
    turnaroundDays: 7,
  },
  {
    code: "HIVGN",
    name: "HIV Genotype",
    department: "Serology / Immunochemistry",
    requiredSampleType: "EDTA Purple Top",
    volume: "6ml",
    turnaroundDays: 14,
  },
  {
    code: "COVIDPCR",
    name: "SARS-CoV-2 PCR",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Swab",
    volume: "N/A",
    turnaroundDays: 1,
  },
  {
    code: "COVIDRAG",
    name: "SARS-CoV-2 Rapid Antigen",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Swab",
    volume: "N/A",
    turnaroundDays: 0,
  },
  {
    code: "HBSAG",
    name: "HBsAg (Hepatitis B Surface Antigen)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "ANTIHCV",
    name: "Anti-HCV (Hepatitis C)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "VDRL",
    name: "VDRL/RPR (Syphilis)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "WIDAL",
    name: "Widal Test",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "BRUC",
    name: "Brucella Antibodies",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "HPYL",
    name: "H. pylori Antigen",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Stool",
    volume: "N/A",
    turnaroundDays: 2,
  },
  {
    code: "ALLERGY",
    name: "Allergy Profile (21-panel)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "10ml",
    turnaroundDays: 21,
    isAllergyProfile: true,
  },
  {
    code: "CA125",
    name: "CA 125 (Ovarian Tumor Marker)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 3,
  },
  {
    code: "CEA",
    name: "CEA (Carcinoembryonic Antigen)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 3,
  },
  {
    code: "CA199",
    name: "CA 19-9",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 3,
  },
  {
    code: "AFP",
    name: "AFP (Alpha-Fetoprotein)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 3,
  },
  {
    code: "FSHLH",
    name: "FSH / LH (Hormonal)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "E2",
    name: "Estradiol (E2)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "PROG",
    name: "Progesterone",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "TEST",
    name: "Testosterone",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "PRL",
    name: "Prolactin",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
  {
    code: "BHCG",
    name: "Beta-HCG (Pregnancy)",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 1,
  },
  {
    code: "CORT",
    name: "Cortisol",
    department: "Serology / Immunochemistry",
    requiredSampleType: "Plain Yellow Top",
    volume: "5ml",
    turnaroundDays: 2,
  },
];

export const DEPARTMENTS = [
  "Haematology",
  "Chemistry",
  "Serology / Immunochemistry",
];

export function getTestsByDepartment(dept: string) {
  return TEST_CATALOG.filter((t) => t.department === dept);
}

export const SAMPLE_TYPES = [
  "EDTA Purple Top",
  "Citrate Blue Top",
  "Plain Yellow Top",
  "Fluoride Grey Top",
  "Swab",
  "Urine",
  "Stool",
];

export const SAMPLE_SOURCES = [
  "Outpatient",
  "Inpatient",
  "Emergency",
  "Walk-in",
  "Referral",
];
