/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SampleStatus = IDL.Variant({
  'referred' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'resultsReceived' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const LaboratorySample = IDL.Record({
  'id' : IDL.Nat,
  'status' : SampleStatus,
  'handler' : IDL.Text,
  'createdAt' : IDL.Int,
  'sampleType' : IDL.Text,
  'sampleSource' : IDL.Text,
  'receivedDate' : IDL.Int,
  'referredTo' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'referralReturned' : IDL.Bool,
});
export const TestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const LaboratorySampleTest = IDL.Record({
  'id' : IDL.Nat,
  'status' : TestStatus,
  'turnaroundDays' : IDL.Nat,
  'testCode' : IDL.Text,
  'resultNotes' : IDL.Text,
  'testName' : IDL.Text,
  'isAllergyProfile' : IDL.Bool,
  'expectedResultDate' : IDL.Int,
  'requiredSampleType' : IDL.Text,
  'department' : IDL.Text,
  'sampleId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestToSample' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSample' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteSample' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'referred' : IDL.Nat,
          'pending' : IDL.Nat,
          'completed' : IDL.Nat,
          'resultsReceived' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSampleById' : IDL.Func([IDL.Nat], [LaboratorySample], ['query']),
  'getSampleTests' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LaboratorySampleTest)],
      ['query'],
    ),
  'getSamples' : IDL.Func([], [IDL.Vec(LaboratorySample)], ['query']),
  'getSamplesByStatus' : IDL.Func(
      [SampleStatus],
      [IDL.Vec(LaboratorySample)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSamples' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LaboratorySample)],
      ['query'],
    ),
  'updateSample' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSampleReferral' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'updateSampleStatus' : IDL.Func([IDL.Nat, SampleStatus], [], []),
  'updateTestStatus' : IDL.Func([IDL.Nat, TestStatus, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SampleStatus = IDL.Variant({
    'referred' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'resultsReceived' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const LaboratorySample = IDL.Record({
    'id' : IDL.Nat,
    'status' : SampleStatus,
    'handler' : IDL.Text,
    'createdAt' : IDL.Int,
    'sampleType' : IDL.Text,
    'sampleSource' : IDL.Text,
    'receivedDate' : IDL.Int,
    'referredTo' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'referralReturned' : IDL.Bool,
  });
  const TestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const LaboratorySampleTest = IDL.Record({
    'id' : IDL.Nat,
    'status' : TestStatus,
    'turnaroundDays' : IDL.Nat,
    'testCode' : IDL.Text,
    'resultNotes' : IDL.Text,
    'testName' : IDL.Text,
    'isAllergyProfile' : IDL.Bool,
    'expectedResultDate' : IDL.Int,
    'requiredSampleType' : IDL.Text,
    'department' : IDL.Text,
    'sampleId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestToSample' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSample' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteSample' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'referred' : IDL.Nat,
            'pending' : IDL.Nat,
            'completed' : IDL.Nat,
            'resultsReceived' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSampleById' : IDL.Func([IDL.Nat], [LaboratorySample], ['query']),
    'getSampleTests' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LaboratorySampleTest)],
        ['query'],
      ),
    'getSamples' : IDL.Func([], [IDL.Vec(LaboratorySample)], ['query']),
    'getSamplesByStatus' : IDL.Func(
        [SampleStatus],
        [IDL.Vec(LaboratorySample)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSamples' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LaboratorySample)],
        ['query'],
      ),
    'updateSample' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSampleReferral' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'updateSampleStatus' : IDL.Func([IDL.Nat, SampleStatus], [], []),
    'updateTestStatus' : IDL.Func([IDL.Nat, TestStatus, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };