/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LaboratorySample {
  'id' : bigint,
  'status' : SampleStatus,
  'handler' : string,
  'createdAt' : bigint,
  'sampleType' : string,
  'sampleSource' : string,
  'receivedDate' : bigint,
  'referredTo' : [] | [string],
  'notes' : string,
  'patientName' : string,
  'referralReturned' : boolean,
}
export interface LaboratorySampleTest {
  'id' : bigint,
  'status' : TestStatus,
  'turnaroundDays' : bigint,
  'testCode' : string,
  'resultNotes' : string,
  'testName' : string,
  'isAllergyProfile' : boolean,
  'expectedResultDate' : bigint,
  'requiredSampleType' : string,
  'department' : string,
  'sampleId' : bigint,
}
export type SampleStatus = { 'referred' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'resultsReceived' : null } |
  { 'inProgress' : null };
export type TestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestToSample' : ActorMethod<
    [bigint, string, string, string, string, bigint, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSample' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'deleteSample' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'referred' : bigint,
      'pending' : bigint,
      'completed' : bigint,
      'resultsReceived' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getSampleById' : ActorMethod<[bigint], LaboratorySample>,
  'getSampleTests' : ActorMethod<[bigint], Array<LaboratorySampleTest>>,
  'getSamples' : ActorMethod<[], Array<LaboratorySample>>,
  'getSamplesByStatus' : ActorMethod<[SampleStatus], Array<LaboratorySample>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSamples' : ActorMethod<[string], Array<LaboratorySample>>,
  'updateSample' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateSampleReferral' : ActorMethod<
    [bigint, [] | [string], boolean],
    undefined
  >,
  'updateSampleStatus' : ActorMethod<[bigint, SampleStatus], undefined>,
  'updateTestStatus' : ActorMethod<[bigint, TestStatus, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];