/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LaboratorySampleTest {
    id: bigint;
    status: TestStatus;
    turnaroundDays: bigint;
    testCode: string;
    resultNotes: string;
    testName: string;
    isAllergyProfile: boolean;
    expectedResultDate: bigint;
    requiredSampleType: string;
    department: string;
    sampleId: bigint;
}
export interface LaboratorySample {
    id: bigint;
    status: SampleStatus;
    handler: string;
    createdAt: bigint;
    sampleType: string;
    sampleSource: string;
    receivedDate: bigint;
    referredTo?: string;
    notes: string;
    patientName: string;
    referralReturned: boolean;
}
export interface UserProfile {
    name: string;
}
export enum SampleStatus {
    referred = "referred",
    pending = "pending",
    completed = "completed",
    resultsReceived = "resultsReceived",
    inProgress = "inProgress"
}
export enum TestStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTestToSample(sampleId: bigint, testCode: string, testName: string, department: string, requiredSampleType: string, turnaroundDays: bigint, isAllergyProfile: boolean): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSample(patientName: string, sampleSource: string, sampleType: string, handler: string, notes: string): Promise<bigint>;
    deleteSample(sampleId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        total: bigint;
        referred: bigint;
        pending: bigint;
        completed: bigint;
        resultsReceived: bigint;
        inProgress: bigint;
    }>;
    getSampleById(sampleId: bigint): Promise<LaboratorySample>;
    getSampleTests(sampleId: bigint): Promise<Array<LaboratorySampleTest>>;
    getSamples(): Promise<Array<LaboratorySample>>;
    getSamplesByStatus(status: SampleStatus): Promise<Array<LaboratorySample>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSamples(patientName: string): Promise<Array<LaboratorySample>>;
    updateSample(sampleId: bigint, patientName: string, sampleSource: string, sampleType: string, handler: string, notes: string): Promise<void>;
    updateSampleReferral(sampleId: bigint, referredTo: string | null, referralReturned: boolean): Promise<void>;
    updateSampleStatus(sampleId: bigint, status: SampleStatus): Promise<void>;
    updateTestStatus(testId: bigint, status: TestStatus, resultNotes: string): Promise<void>;
}
import type { LaboratorySample as _LaboratorySample, LaboratorySampleTest as _LaboratorySampleTest, SampleStatus as _SampleStatus, TestStatus as _TestStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTestToSample(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestToSample(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestToSample(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSample(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSample(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSample(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteSample(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSample(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSample(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        total: bigint;
        referred: bigint;
        pending: bigint;
        completed: bigint;
        resultsReceived: bigint;
        inProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getSampleById(arg0: bigint): Promise<LaboratorySample> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleById(arg0);
                return from_candid_LaboratorySample_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleById(arg0);
            return from_candid_LaboratorySample_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSampleTests(arg0: bigint): Promise<Array<LaboratorySampleTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleTests(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleTests(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSamples(): Promise<Array<LaboratorySample>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSamples();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSamples();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSamplesByStatus(arg0: SampleStatus): Promise<Array<LaboratorySample>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSamplesByStatus(to_candid_SampleStatus_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSamplesByStatus(to_candid_SampleStatus_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchSamples(arg0: string): Promise<Array<LaboratorySample>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSamples(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSamples(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSample(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSample(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSample(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSampleReferral(arg0: bigint, arg1: string | null, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleReferral(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleReferral(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateSampleStatus(arg0: bigint, arg1: SampleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleStatus(arg0, to_candid_SampleStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleStatus(arg0, to_candid_SampleStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestStatus(arg0: bigint, arg1: TestStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestStatus(arg0, to_candid_TestStatus_n20(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestStatus(arg0, to_candid_TestStatus_n20(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_LaboratorySampleTest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LaboratorySampleTest): LaboratorySampleTest {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LaboratorySample_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LaboratorySample): LaboratorySample {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SampleStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleStatus): SampleStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TestStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestStatus): TestStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TestStatus;
    turnaroundDays: bigint;
    testCode: string;
    resultNotes: string;
    testName: string;
    isAllergyProfile: boolean;
    expectedResultDate: bigint;
    requiredSampleType: string;
    department: string;
    sampleId: bigint;
}): {
    id: bigint;
    status: TestStatus;
    turnaroundDays: bigint;
    testCode: string;
    resultNotes: string;
    testName: string;
    isAllergyProfile: boolean;
    expectedResultDate: bigint;
    requiredSampleType: string;
    department: string;
    sampleId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TestStatus_n14(_uploadFile, _downloadFile, value.status),
        turnaroundDays: value.turnaroundDays,
        testCode: value.testCode,
        resultNotes: value.resultNotes,
        testName: value.testName,
        isAllergyProfile: value.isAllergyProfile,
        expectedResultDate: value.expectedResultDate,
        requiredSampleType: value.requiredSampleType,
        department: value.department,
        sampleId: value.sampleId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SampleStatus;
    handler: string;
    createdAt: bigint;
    sampleType: string;
    sampleSource: string;
    receivedDate: bigint;
    referredTo: [] | [string];
    notes: string;
    patientName: string;
    referralReturned: boolean;
}): {
    id: bigint;
    status: SampleStatus;
    handler: string;
    createdAt: bigint;
    sampleType: string;
    sampleSource: string;
    receivedDate: bigint;
    referredTo?: string;
    notes: string;
    patientName: string;
    referralReturned: boolean;
} {
    return {
        id: value.id,
        status: from_candid_SampleStatus_n8(_uploadFile, _downloadFile, value.status),
        handler: value.handler,
        createdAt: value.createdAt,
        sampleType: value.sampleType,
        sampleSource: value.sampleSource,
        receivedDate: value.receivedDate,
        referredTo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.referredTo)),
        notes: value.notes,
        patientName: value.patientName,
        referralReturned: value.referralReturned
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TestStatus {
    return "pending" in value ? TestStatus.pending : "completed" in value ? TestStatus.completed : "inProgress" in value ? TestStatus.inProgress : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referred: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    resultsReceived: null;
} | {
    inProgress: null;
}): SampleStatus {
    return "referred" in value ? SampleStatus.referred : "pending" in value ? SampleStatus.pending : "completed" in value ? SampleStatus.completed : "resultsReceived" in value ? SampleStatus.resultsReceived : "inProgress" in value ? SampleStatus.inProgress : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LaboratorySampleTest>): Array<LaboratorySampleTest> {
    return value.map((x)=>from_candid_LaboratorySampleTest_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LaboratorySample>): Array<LaboratorySample> {
    return value.map((x)=>from_candid_LaboratorySample_n6(_uploadFile, _downloadFile, x));
}
function to_candid_SampleStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleStatus): _SampleStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TestStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestStatus): _TestStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleStatus): {
    referred: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    resultsReceived: null;
} | {
    inProgress: null;
} {
    return value == SampleStatus.referred ? {
        referred: null
    } : value == SampleStatus.pending ? {
        pending: null
    } : value == SampleStatus.completed ? {
        completed: null
    } : value == SampleStatus.resultsReceived ? {
        resultsReceived: null
    } : value == SampleStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TestStatus.pending ? {
        pending: null
    } : value == TestStatus.completed ? {
        completed: null
    } : value == TestStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
